// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1610814346);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1610814316);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8dfd02d5-4fb1-44bc-8ed7-2a1a3cad4046}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1610814351130");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1610816139130");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1610814321528");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1610835921528");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1610814320");
user_pref("browser.slowStartup.averageTime", 3026);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210105204613");
user_pref("browser.startup.homepage_override.mstone", "78.6.1");
user_pref("browser.startup.lastColdStartupCheck", 1610814318);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1610814321635");
user_pref("distribution.iniFile.exists.appversion", "78.6.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "79315ad2d88647688e2805118c85ed95");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.6.1");
user_pref("extensions.lastPlatformVersion", "78.6.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"29e93d8b-ed55-4757-8ac5-dca1345865ad\",\"formautofill@mozilla.org\":\"6b396e8a-8a2a-4371-b6fc-5d07cca4f5d8\",\"screenshots@mozilla.org\":\"85579cce-11b4-4176-a934-962b7f683cbd\",\"webcompat-reporter@mozilla.org\":\"a4beda64-5659-476e-9ed5-9d75a0b75d3b\",\"webcompat@mozilla.org\":\"36df6ee1-46a3-4872-b9ab-7fd0fc14f679\",\"default-theme@mozilla.org\":\"9514acfd-4a12-4358-ba20-e46f6e7c61f2\",\"google@search.mozilla.org\":\"2af0749d-19d1-4053-a99b-ca747229f0a4\",\"amazondotcom@search.mozilla.org\":\"df7d3d10-18d7-4ae6-9910-eb1da07dab28\",\"wikipedia@search.mozilla.org\":\"7f44bc82-9a89-44f1-9bfe-112c2c838d0d\",\"bing@search.mozilla.org\":\"d3a9aac8-c8b1-4905-a337-9f876912edd1\",\"ddg@search.mozilla.org\":\"bcad2b7a-dff2-4606-accd-01df4192878d\",\"ebay@search.mozilla.org\":\"e8b6c0f7-278e-48bd-aef9-08ee87e32d75\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "aef30f37-44d5-41b7-87a9-37ac595515b3");
user_pref("security.sandbox.plugin.tempDirSuffix", "873ba0ce-ebc6-4d3a-bdde-d35411cb51fc");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1610814315);
user_pref("toolkit.telemetry.cachedClientID", "cb8ef8e9-15f4-4126-8e70-77aac41ac77b");
user_pref("toolkit.telemetry.previousBuildID", "20210105204613");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
